add DTO Mapper to the project
Mariana-VV/BookStoreApp pull request #2
Opened 2024-05-23 11:57 UTC by Mariana-VV

2024-05-23 14:43 UTC, MAMentorFX requested changes

2024-05-23 14:43 UTC, MAMentorFX commented on pom.xml
> +<!--            </plugin>-->
remove comments

2024-05-23 14:43 UTC, MAMentorFX commented on src/main/java/org/bookstore/dto/BookDto.java
> +@Setter
for DTOs suggest @Data instead of Setter and Getter.

2024-05-23 14:43 UTC, MAMentorFX commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-05-23 14:43 UTC, MAMentorFX commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +                new EntityNotFoundException("Cant fint book by id " + id));
```suggestion
                new EntityNotFoundException("Cant fint book by id: " + id));
```

2024-05-23 14:43 UTC, MAMentorFX commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-05-24 06:58 UTC, Vasul-Pankiv approved these changes

2024-05-24 09:49 UTC, merged