Java persistence JPA
Mariana-VV/BookStoreApp pull request #3
Opened 2024-05-26 11:52 UTC by Mariana-VV

2024-05-26 13:22 UTC, okuzan requested changes

2024-05-26 13:22 UTC, okuzan commented on src/main/java/org/bookstore/model/Book.java
> +@Where(clause = "is_deleted=false")
Where is deprecated, use SQLrestriction

2024-05-26 13:22 UTC, okuzan commented on src/main/java/org/bookstore/model/Book.java
> +    //    @ToString.Exclude
don't leave commented code, just remove it, we can get it from git when needed

2024-05-26 13:22 UTC, okuzan commented on src/main/java/org/bookstore/repository/BookRepository.java
> +    // nativeQuery = true)
same

2024-05-26 13:22 UTC, okuzan commented on src/main/resources/db/changelog/changes/01-create-books-table.yaml
> +                    nullable: false
this file doesn't end with an empty line

2024-05-26 13:22 UTC, okuzan commented on pom.xml
> +
```suggestion
```

2024-05-26 13:22 UTC, okuzan commented on src/main/java/org/bookstore/controller/BookController.java
> +    @GetMapping("/by-title")//http://localhost:8080/api/books/by-title?title=matrix
```suggestion
    @GetMapping
```
In RESTful design, the URL should ideally represent a resource and not include verbs or actions. RESTful URLs should be nouns and represent the resources being accessed. In this case, the URL is designed to find books by title, but it includes a query parameter that specifies the title.

A more RESTful approach would be to use a URL that represents the books resource and include the title as part of the resource path or as a query parameter in a more resource-centric way.

2024-05-26 14:10 UTC, MAMentorFX requested changes

2024-05-26 14:10 UTC, MAMentorFX commented on src/main/java/org/bookstore/controller/BookController.java
> +    @GetMapping("/title")
Not the best endpoint. localhost:8080/title?title="Sherlock". there are two `title` in uri

2024-05-26 14:10 UTC, MAMentorFX commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +                .toList();
Mapstruct supports mapping collections from the box

2024-05-26 14:10 UTC, MAMentorFX commented on src/main/java/org/bookstore/service/impl/BookServiceImpl.java
> +    public BookDto update(Long id, CreateBookRequestDto requestDto) {
@Transactional. You make more than one call to DB

2024-05-27 10:27 UTC, MentorMateAcademy approved these changes

2024-05-27 10:52 UTC, merged